import { lato } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Provider from "@/lib/ThemeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background text-foreground",
          lato.variable
        )}
      >
        <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
